import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import TopNav from "./_components/topnav";
import { Toaster } from "sonner";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="dark">
          <div className="grid h-screen grid-rows-[auto,1fr]">
            <TopNav />
            <TRPCReactProvider>
              <main className="overflow-y-scroll">{children}</main>
            </TRPCReactProvider>
          </div>

          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
