import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

import TopNav from "./_components/topnav";
import { TRPCReactProvider } from "~/trpc/react";
import { Providers } from "./providers";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${GeistSans.variable}`}
        suppressHydrationWarning
      >
        <body>
          <Providers>
            <div className="grid h-screen grid-rows-[auto,1fr]">
              <TopNav />
              <TRPCReactProvider>
                <main className="overflow-y-scroll">{children}</main>
              </TRPCReactProvider>
            </div>

            <Toaster />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
